# This is a basic workflow to help you get started with Actions

name: Blob storage website CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS_SA20220727X01 }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name sa20220727x01 --auth-mode key -d '$web' -s ./frontend/
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "azurecdn20220728x01" --name "azurecdn20220728x01" --resource-group "RG-20220727-azure-resume-project"

  # Azure logout
    - name: logout
      run: |
            az logout
      if: always()
