name: Run Azure Login with OpenID Connect
on: [push]

permissions:
      id-token: write
      contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd

    - name: Upload to blob storage
      run: az storage blob upload-batch --account-name sa20220727x01 --auth-mode key -d '$web' -s .

    - name: Purge CDN endpoint
      run: az cdn endpoint purge --content-paths  "/*" --profile-name "azurecdn20220728x01" --name "azurecdn20220728x01" --resource-group "RG-20220727-azure-resume-project"